
classdef defuzzy_vel_modif < ros.Message
    %defuzzy_vel_modif MATLAB implementation of wpg/defuzzy_vel_modif
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wpg/defuzzy_vel_modif' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f5bbe35e00f4d77e7db3b1acb0535cd7' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'NewVelocity' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'new_velocity' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        NewVelocity
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'defuzzy_vel_modif', 'Header')
            obj.Header = val;
        end
        function set.NewVelocity(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'defuzzy_vel_modif', 'NewVelocity');
            obj.NewVelocity = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wpg.defuzzy_vel_modif.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wpg.defuzzy_vel_modif(strObj);
        end
    end
end
