
classdef fuzzy_lcs < ros.Message
    %fuzzy_lcs MATLAB implementation of wpg/fuzzy_lcs
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wpg/fuzzy_lcs' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e9f41507ebff207581dd2a249f72e7c2' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'KP' 'KI' 'KD' 'ObjVel' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'kP' 'kI' 'kD' 'obj_vel' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        KP
        KI
        KD
        ObjVel
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'fuzzy_lcs', 'Header')
            obj.Header = val;
        end
        function set.KP(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'fuzzy_lcs', 'KP');
            obj.KP = double(val);
        end
        function set.KI(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'fuzzy_lcs', 'KI');
            obj.KI = double(val);
        end
        function set.KD(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'fuzzy_lcs', 'KD');
            obj.KD = double(val);
        end
        function set.ObjVel(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'fuzzy_lcs', 'ObjVel');
            obj.ObjVel = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wpg.fuzzy_lcs.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wpg.fuzzy_lcs(strObj);
        end
    end
end
