
classdef fuzzy < ros.Message
    %fuzzy MATLAB implementation of wpg/fuzzy
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wpg/fuzzy' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'a369fa74dd9c10ab03af42e68eb33e4c' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Error' 'DError' 'PVal' 'IVal' 'DVal' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'Error' 'D_Error' 'P_val' 'I_val' 'D_val' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Error
        DError
        PVal
        IVal
        DVal
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'fuzzy', 'Header')
            obj.Header = val;
        end
        function set.Error(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'fuzzy', 'Error');
            obj.Error = double(val);
        end
        function set.DError(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'fuzzy', 'DError');
            obj.DError = double(val);
        end
        function set.PVal(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'fuzzy', 'PVal');
            obj.PVal = double(val);
        end
        function set.IVal(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'fuzzy', 'IVal');
            obj.IVal = double(val);
        end
        function set.DVal(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'fuzzy', 'DVal');
            obj.DVal = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wpg.fuzzy.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wpg.fuzzy(strObj);
        end
    end
end
