// Generated by gencpp from file wpg/defuzzy_vel_modif.msg
// DO NOT EDIT!


#ifndef WPG_MESSAGE_DEFUZZY_VEL_MODIF_H
#define WPG_MESSAGE_DEFUZZY_VEL_MODIF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace wpg
{
template <class ContainerAllocator>
struct defuzzy_vel_modif_
{
  typedef defuzzy_vel_modif_<ContainerAllocator> Type;

  defuzzy_vel_modif_()
    : header()
    , new_velocity(0.0)  {
    }
  defuzzy_vel_modif_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , new_velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _new_velocity_type;
  _new_velocity_type new_velocity;





  typedef boost::shared_ptr< ::wpg::defuzzy_vel_modif_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wpg::defuzzy_vel_modif_<ContainerAllocator> const> ConstPtr;

}; // struct defuzzy_vel_modif_

typedef ::wpg::defuzzy_vel_modif_<std::allocator<void> > defuzzy_vel_modif;

typedef boost::shared_ptr< ::wpg::defuzzy_vel_modif > defuzzy_vel_modifPtr;
typedef boost::shared_ptr< ::wpg::defuzzy_vel_modif const> defuzzy_vel_modifConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wpg::defuzzy_vel_modif_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wpg::defuzzy_vel_modif_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wpg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'wpg': ['/home/lucas/catkin_ws/src/matlab_msg_gen_ros1/glnxa64/src/wpg/msg'], 'std_msgs': ['/home/lucas/Matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/home/lucas/Matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wpg::defuzzy_vel_modif_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wpg::defuzzy_vel_modif_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpg::defuzzy_vel_modif_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpg::defuzzy_vel_modif_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpg::defuzzy_vel_modif_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpg::defuzzy_vel_modif_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wpg::defuzzy_vel_modif_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5bbe35e00f4d77e7db3b1acb0535cd7";
  }

  static const char* value(const ::wpg::defuzzy_vel_modif_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5bbe35e00f4d77eULL;
  static const uint64_t static_value2 = 0x7db3b1acb0535cd7ULL;
};

template<class ContainerAllocator>
struct DataType< ::wpg::defuzzy_vel_modif_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wpg/defuzzy_vel_modif";
  }

  static const char* value(const ::wpg::defuzzy_vel_modif_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wpg::defuzzy_vel_modif_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 new_velocity\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::wpg::defuzzy_vel_modif_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wpg::defuzzy_vel_modif_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.new_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct defuzzy_vel_modif_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wpg::defuzzy_vel_modif_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wpg::defuzzy_vel_modif_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "new_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.new_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WPG_MESSAGE_DEFUZZY_VEL_MODIF_H
