// Generated by gencpp from file wpg/defuzzyfied.msg
// DO NOT EDIT!


#ifndef WPG_MESSAGE_DEFUZZYFIED_H
#define WPG_MESSAGE_DEFUZZYFIED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace wpg
{
template <class ContainerAllocator>
struct defuzzyfied_
{
  typedef defuzzyfied_<ContainerAllocator> Type;

  defuzzyfied_()
    : header()
    , Delta_P_val(0.0)
    , Delta_I_val(0.0)
    , Delta_D_val(0.0)  {
    }
  defuzzyfied_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Delta_P_val(0.0)
    , Delta_I_val(0.0)
    , Delta_D_val(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _Delta_P_val_type;
  _Delta_P_val_type Delta_P_val;

   typedef double _Delta_I_val_type;
  _Delta_I_val_type Delta_I_val;

   typedef double _Delta_D_val_type;
  _Delta_D_val_type Delta_D_val;





  typedef boost::shared_ptr< ::wpg::defuzzyfied_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wpg::defuzzyfied_<ContainerAllocator> const> ConstPtr;

}; // struct defuzzyfied_

typedef ::wpg::defuzzyfied_<std::allocator<void> > defuzzyfied;

typedef boost::shared_ptr< ::wpg::defuzzyfied > defuzzyfiedPtr;
typedef boost::shared_ptr< ::wpg::defuzzyfied const> defuzzyfiedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wpg::defuzzyfied_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wpg::defuzzyfied_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wpg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'wpg': ['/home/lucas/catkin_ws/src/matlab_msg_gen_ros1/glnxa64/src/wpg/msg'], 'std_msgs': ['/home/lucas/Matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/home/lucas/Matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wpg::defuzzyfied_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wpg::defuzzyfied_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpg::defuzzyfied_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpg::defuzzyfied_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpg::defuzzyfied_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpg::defuzzyfied_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wpg::defuzzyfied_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c61101eb17757098c6b57a2303f403e4";
  }

  static const char* value(const ::wpg::defuzzyfied_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc61101eb17757098ULL;
  static const uint64_t static_value2 = 0xc6b57a2303f403e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::wpg::defuzzyfied_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wpg/defuzzyfied";
  }

  static const char* value(const ::wpg::defuzzyfied_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wpg::defuzzyfied_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 Delta_P_val\n"
"float64 Delta_I_val\n"
"float64 Delta_D_val\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::wpg::defuzzyfied_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wpg::defuzzyfied_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Delta_P_val);
      stream.next(m.Delta_I_val);
      stream.next(m.Delta_D_val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct defuzzyfied_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wpg::defuzzyfied_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wpg::defuzzyfied_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Delta_P_val: ";
    Printer<double>::stream(s, indent + "  ", v.Delta_P_val);
    s << indent << "Delta_I_val: ";
    Printer<double>::stream(s, indent + "  ", v.Delta_I_val);
    s << indent << "Delta_D_val: ";
    Printer<double>::stream(s, indent + "  ", v.Delta_D_val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WPG_MESSAGE_DEFUZZYFIED_H
