// Generated by gencpp from file wpg/fuzzy_lcs.msg
// DO NOT EDIT!


#ifndef WPG_MESSAGE_FUZZY_LCS_H
#define WPG_MESSAGE_FUZZY_LCS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace wpg
{
template <class ContainerAllocator>
struct fuzzy_lcs_
{
  typedef fuzzy_lcs_<ContainerAllocator> Type;

  fuzzy_lcs_()
    : header()
    , kP(0.0)
    , kI(0.0)
    , kD(0.0)
    , obj_vel(0.0)  {
    }
  fuzzy_lcs_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , kP(0.0)
    , kI(0.0)
    , kD(0.0)
    , obj_vel(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _kP_type;
  _kP_type kP;

   typedef double _kI_type;
  _kI_type kI;

   typedef double _kD_type;
  _kD_type kD;

   typedef double _obj_vel_type;
  _obj_vel_type obj_vel;





  typedef boost::shared_ptr< ::wpg::fuzzy_lcs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wpg::fuzzy_lcs_<ContainerAllocator> const> ConstPtr;

}; // struct fuzzy_lcs_

typedef ::wpg::fuzzy_lcs_<std::allocator<void> > fuzzy_lcs;

typedef boost::shared_ptr< ::wpg::fuzzy_lcs > fuzzy_lcsPtr;
typedef boost::shared_ptr< ::wpg::fuzzy_lcs const> fuzzy_lcsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wpg::fuzzy_lcs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wpg::fuzzy_lcs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wpg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'wpg': ['/home/lucas/catkin_ws/src/matlab_msg_gen_ros1/glnxa64/src/wpg/msg'], 'std_msgs': ['/home/lucas/Matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/home/lucas/Matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wpg::fuzzy_lcs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wpg::fuzzy_lcs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpg::fuzzy_lcs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpg::fuzzy_lcs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpg::fuzzy_lcs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpg::fuzzy_lcs_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wpg::fuzzy_lcs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9f41507ebff207581dd2a249f72e7c2";
  }

  static const char* value(const ::wpg::fuzzy_lcs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9f41507ebff2075ULL;
  static const uint64_t static_value2 = 0x81dd2a249f72e7c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::wpg::fuzzy_lcs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wpg/fuzzy_lcs";
  }

  static const char* value(const ::wpg::fuzzy_lcs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wpg::fuzzy_lcs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 kP\n"
"float64 kI\n"
"float64 kD\n"
"float64 obj_vel\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::wpg::fuzzy_lcs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wpg::fuzzy_lcs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.kP);
      stream.next(m.kI);
      stream.next(m.kD);
      stream.next(m.obj_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fuzzy_lcs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wpg::fuzzy_lcs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wpg::fuzzy_lcs_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "kP: ";
    Printer<double>::stream(s, indent + "  ", v.kP);
    s << indent << "kI: ";
    Printer<double>::stream(s, indent + "  ", v.kI);
    s << indent << "kD: ";
    Printer<double>::stream(s, indent + "  ", v.kD);
    s << indent << "obj_vel: ";
    Printer<double>::stream(s, indent + "  ", v.obj_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WPG_MESSAGE_FUZZY_LCS_H
