
classdef defuzzyfied < ros.Message
    %defuzzyfied MATLAB implementation of wpg/defuzzyfied
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wpg/defuzzyfied' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'c61101eb17757098c6b57a2303f403e4' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'DeltaPVal' 'DeltaIVal' 'DeltaDVal' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'Delta_P_val' 'Delta_I_val' 'Delta_D_val' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        DeltaPVal
        DeltaIVal
        DeltaDVal
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'defuzzyfied', 'Header')
            obj.Header = val;
        end
        function set.DeltaPVal(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'defuzzyfied', 'DeltaPVal');
            obj.DeltaPVal = double(val);
        end
        function set.DeltaIVal(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'defuzzyfied', 'DeltaIVal');
            obj.DeltaIVal = double(val);
        end
        function set.DeltaDVal(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'defuzzyfied', 'DeltaDVal');
            obj.DeltaDVal = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wpg.defuzzyfied.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wpg.defuzzyfied(strObj);
        end
    end
end
