// Generated by gencpp from file wpg/fuzzy_vel_modif.msg
// DO NOT EDIT!


#ifndef WPG_MESSAGE_FUZZY_VEL_MODIF_H
#define WPG_MESSAGE_FUZZY_VEL_MODIF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace wpg
{
template <class ContainerAllocator>
struct fuzzy_vel_modif_
{
  typedef fuzzy_vel_modif_<ContainerAllocator> Type;

  fuzzy_vel_modif_()
    : header()
    , distance_to_obstacle(0.0)
    , distance_to_objective(0.0)
    , velocity(0.0)  {
    }
  fuzzy_vel_modif_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance_to_obstacle(0.0)
    , distance_to_objective(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _distance_to_obstacle_type;
  _distance_to_obstacle_type distance_to_obstacle;

   typedef double _distance_to_objective_type;
  _distance_to_objective_type distance_to_objective;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::wpg::fuzzy_vel_modif_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wpg::fuzzy_vel_modif_<ContainerAllocator> const> ConstPtr;

}; // struct fuzzy_vel_modif_

typedef ::wpg::fuzzy_vel_modif_<std::allocator<void> > fuzzy_vel_modif;

typedef boost::shared_ptr< ::wpg::fuzzy_vel_modif > fuzzy_vel_modifPtr;
typedef boost::shared_ptr< ::wpg::fuzzy_vel_modif const> fuzzy_vel_modifConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wpg::fuzzy_vel_modif_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wpg::fuzzy_vel_modif_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wpg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'wpg': ['/home/lucas/catkin_ws/src/matlab_msg_gen_ros1/glnxa64/src/wpg/msg'], 'std_msgs': ['/home/lucas/Matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/home/lucas/Matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wpg::fuzzy_vel_modif_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wpg::fuzzy_vel_modif_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpg::fuzzy_vel_modif_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpg::fuzzy_vel_modif_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpg::fuzzy_vel_modif_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpg::fuzzy_vel_modif_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wpg::fuzzy_vel_modif_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2387584165a79fa8903721b2c12404b6";
  }

  static const char* value(const ::wpg::fuzzy_vel_modif_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2387584165a79fa8ULL;
  static const uint64_t static_value2 = 0x903721b2c12404b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::wpg::fuzzy_vel_modif_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wpg/fuzzy_vel_modif";
  }

  static const char* value(const ::wpg::fuzzy_vel_modif_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wpg::fuzzy_vel_modif_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 distance_to_obstacle\n"
"float64 distance_to_objective\n"
"float64 velocity\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::wpg::fuzzy_vel_modif_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wpg::fuzzy_vel_modif_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance_to_obstacle);
      stream.next(m.distance_to_objective);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fuzzy_vel_modif_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wpg::fuzzy_vel_modif_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wpg::fuzzy_vel_modif_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance_to_obstacle: ";
    Printer<double>::stream(s, indent + "  ", v.distance_to_obstacle);
    s << indent << "distance_to_objective: ";
    Printer<double>::stream(s, indent + "  ", v.distance_to_objective);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WPG_MESSAGE_FUZZY_VEL_MODIF_H
